name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Run Gradle Publish to Maven Local
        run: ./gradlew publishToMavenLocal

#      - name: Upload artifact to GitHub Packages
#        uses: actions/upload-artifact@v3
#        with:
#          name: maven-artifact
#          path:
