name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: 'COMMIT'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

